import 'ai_message.dart';

/// Represents the standardized output from a chat-based AI model call.
class AiChatResponse {
  /// The primary message generated by the model.
  final AiMessage message;

  /// Optional reasoning content from the model.
  ///
  /// This could include internal thoughts, steps taken, or other metadata
  /// provided by the API.
  final String? reasoning;

  /// A unique identifier for the response, if provided by the API.
  final String? id;

  /// The model that generated the response.
  final String? model;

  const AiChatResponse({
    required this.message,
    this.reasoning,
    this.id,
    this.model,
  });
}

/// Represents a chunk of a streamed chat response.
class AiChatResponseChunk {
  /// The partial message content of the chunk.
  final String? content;

  /// Optional reasoning content from the model for this chunk.
  final String? reasoning;

  /// The model that generated the response.
  final String? model;

  const AiChatResponseChunk({
    this.content,
    this.reasoning,
    this.model,
  });
}
