
/// Represents a request from the model to call a specific tool.
class AiToolCall {
  /// The unique identifier for this tool call.
  final String id;

  /// The name of the function that the model wants to call.
  final String name;

  /// The arguments to call the function with, as generated by the model.
  ///
  /// Note: The model does not always generate valid JSON, and may hallucinate
  /// parameters not defined in your function schema. Validate the arguments
  /// in your code before calling your function.
  final String arguments;

  const AiToolCall({
    required this.id,
    required this.name,
    required this.arguments,
  });
}
